version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  # version: 2.1
  build:
    jobs:
      - cypress/install:
          filters:
            branches:
              only:
              - master
              - develop
          build: npm run build
      - cypress/run:
          filters:
            branches:
              only:
              - master
              - develop
          requires:
            - cypress/install
          start: npm start
          
    
